spring.application.name=ecom
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username = postgres
spring.datasource.password=Moin@99

spring.jpa.hibernate.ddl-auto=update
